name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Bajar el c贸digo
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      # 2. Loguearse en Docker Hub
      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir la imagen y subirla a la nube
      - name: Construir y Subir (Push)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # IMPORTANTE: Reemplaza 'nombre-de-tu-app' por el nombre que quieras
          tags: ${{ secrets.DOCKER_USERNAME }}/mcore-app:latest

      # 4. Conectarse a AWS y actualizar
      - name: Desplegar en AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Detener el contenedor anterior si existe
            docker stop mi-contenedor || true
            docker rm mi-contenedor || true
            
            # Descargar la nueva versi贸n
            docker pull ${{ secrets.DOCKER_USERNAME }}/mcore-app:latest
            
            # Correr la nueva versi贸n (Puerto 3000)
            docker run -d -p 8080:8080 --name mi-contenedor ${{ secrets.DOCKER_USERNAME }}/mcore-app:latest